language: generic
sudo: required
services:
  - docker

# build test images
before_install:
  - docker build -t dbarattinipg/client-test -f ./client/Dockerfile.dev ./client

# run tests
script:
  - docker run -e CI=true dbarattinipg/client-test yarn test

# build and push production images to dockerhub
after_success:
  # build production images
  - docker build -t dbarattinipg/complex-client ./client
  - docker build -t dbarattinipg/complex-nginx ./nginx
  - docker build -t dbarattinipg/complex-server ./server
  - docker build -t dbarattinipg/complex-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push production images to dockerhub
  - docker push dbarattinipg/complex-client
  - docker push dbarattinipg/complex-nginx
  - docker push dbarattinipg/complex-server
  - docker push dbarattinipg/complex-worker

# deploy to aws
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'complex-docker'
  env: 'Complexdocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-375846244399'
  bucket_path: 'docker-complex'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
